# Manual CI for .NET 6.0 legacy support. 
# Not auto-triggered: We only maintain v6.0 support for older version compatibility.
name: "Legacy Support: .NET 6.0 Build & Test"

on:
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  dotnet6-build-and-unit-test:
    name: Build & Test (.NET 6.0) - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ccd8616d44fd3846e67624a50d5aad6d37bf2d25 # v2.22.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Setup .NET SDKs
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: | 
            6.0.x
            8.0.x

      - name: Restore
        run: dotnet restore

      - name: Build (Debug)
        run: dotnet build --configuration Debug --framework net6.0 --no-restore

      - name: Test
        run: dotnet test --no-build --configuration Debug --framework net6.0 --no-restore Adyen.Test/Adyen.Test.csproj